// home layout
// home 은 큐레이션을 위한 경로이다.
//
import {AppSidebar} from '@/components/HomeSidebar';
import {SidebarProvider, SidebarTrigger} from '@/components/ui/sidebar';
import type {Metadata} from 'next';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SidebarProvider>
            <AppSidebar />
            <SidebarTrigger />
            {children}
        </SidebarProvider>
    );
}
